# Generated by Django 5.2 on 2025-05-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_alter_business_options_business_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
