# Generated by Django 5.2 on 2025-05-28 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_business_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={},
        ),
        migrations.RemoveField(
            model_name='business',
            name='city',
        ),
        migrations.RemoveField(
            model_name='business',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='business',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='business',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='business',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businesses', to='businesses.category'),
        ),
    ]
