# Generated by Django 5.2 on 2025-05-28 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_alter_business_options_remove_business_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'verbose_name_plural': 'Businesses'},
        ),
    ]
