"""
Django settings for local_business_directory project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@e^v93b^9z2#4n0!@$1=9u#x^k+q4x48t&d^4p5v@^b8x#+*1' # KEEP THIS UNIQUE TO YOUR PROJECT!

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True # Set to False in production

ALLOWED_HOSTS = ['local-business-directory-3-fmh8.onrender.com', '.render.com'] # In development, this is fine. For production, add your domain/IP, e.g., ['yourdomain.com', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'businesses', # <--- Your custom app
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'local_business_directory.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Add the directory for your project-level templates (like homepage.html)
        'DIRS': [BASE_DIR /  'templates'],
        'APP_DIRS': True, # This tells Django to look for 'templates' folders inside your apps
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'local_business_directory.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/' # The URL prefix for static files served in development
LOGIN_URL = 'login'                 # Login page ka URL (Django ke auth URLs mein 'login' naam se hota hai)
LOGOUT_REDIRECT_URL = 'businesses:list'
LOGIN_REDIRECT_URL = 'businesses:list'

# Optional: Where Django will collect all static files for production deployment
# STATIC_ROOT = BASE_DIR / 'staticfiles'

# Optional: List of additional locations of static files (for project-wide static files)
# STATICFILES_DIRS = [
#     BASE_DIR / "static",
# ]


# Media files (for user uploads like images)
# These settings are crucial for handling uploaded content like business images.
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media' # This is the absolute path to the directory where user-uploaded files will be stored.


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# myproject/local_business_directory/myproject/settings.py

# ... (rest of your settings.py file content) ...

# Password Reset Email Settings (for testing)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST = 'localhost' # Not used with console backend, but good practice
EMAIL_PORT = 1025 # Not used with console backend, but good practice